### ISSUE TITLE
How to extend plot on armadillo matrix?

### ISSUE THREAD

**Issue by erusyd** [X-Neon/gdbplotlib#1]
I can extend `plot` to armadillo `vec` type easily according to [gdb_armadillo_helpers](https://github.com/darcamo/gdb_armadillo_helpers), but failed for `mat` type. I want to plot the matrix column-wise just like MATLAB `plot`. Can you give me some clues?

**Comment by X-Neon** [comment]
Could you be more specific with the issue you're having? I'm not familiar with Armadillo types, but at a quick glance, the matrix class seems pretty standard, with a pointer to some column-ordered data. If so, something like this would probably work:

```python
class ArmadilloMat(TypeHandler):
    @staticmethod
    def can_handle(gdb_type: gdb.Type) -> bool:
        return str(gdb_type).startswith("arma::Mat")

    def shape(self, gdb_value: gdb.Value) -> Tuple[Optional[int], ...]:
        n_cols = int(gdb_value["n_cols"])
        n_rows = int(gdb_value["n_rows"])
        return (n_rows, n_cols)

    def contained_type(self, gdb_value: gdb.Value) -> gdb.Type:
        return gdb_value.type.template_argument(0)

    def extract(self, gdb_value: gdb.Value, index: Tuple[int, ...]):
        n_rows = int(gdb_value["n_rows"])
        return (gdb_value["mem"] + index[1] * n_rows + index[0]).dereference()
```

I may have gotten rows/columns mixed up at some point in there, I'm far more used to row-based indexing. I hope this helps

**Comment by erusyd** [comment]
Thanks. In order to plot the same figure as MATLAB plot matrix, I need to transpose my armadillo matrix first.
