### ISSUE TITLE
Multiple plot windows?

### ISSUE THREAD

**Issue by kzhuang1** [X-Neon/gdbplotlib#2]
Hi I would like to be able to plot multiple buffers to compare and view different data at the same time, could you give me some clues on how to implement this? Also how would I add the ability to plot a 2d array using imagesc? Thanks so much, this package works very well.

**Comment by X-Neon** [comment]
To plot multiple things on the same plot, just give multiple arguments to the `plot` command. For example, to simultaneously plot `x`, `y`, and `z`, run `plot x y z`.

I'm not familiar with imagesc, but a quick Google suggests that it's a Matlab command for 2D heatmaps? If so, I would take a look at the `plot.py` file, so you can add a new plot command. I imagine it will look similar to the existing `Plot3D` class given that it's for plotting 2D data, except you'll replace the `matplotlib` command for 3D plotting with 2D heatmaps. In the past, I've used [imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html) to achieve that.

**Comment by kzhuang1** [comment]
Ahh sorry I mean that right now I need to close a previous window for the next plot window to show up, is there a way to get it to open a new window every time a plot call is made in gdb?

**Comment by X-Neon** [comment]
I don't belive so. `plt.show()` is a blocking call, so nothing else can be processed while a window is open. Normally you would set `plt.ion()` to set interactive mode, but when I tried this it didn't work. You could try setting `plt.ion()` yourself, or doing `plot.show(block=False)` and see if you have more luck than I did

**Comment by kzhuang1** [comment]
It took me way too long to figure it out and its still very very buggy, but instead of using the global plt space if you encapsulate the plotting function in a object i.e. figureObj = plt.figure() and newplot = figureObj .add_subplot(111), if you use figureObj.show() with a pause call it allows you to have a new window every time you call plot, there are a bunch of bugs however with some windows randomly blanking themselves sometimes when another is created, the windows also become non-interactive, and will immediately close without a short pause call (dont know why a few milisecond pause is needed), but this is a step towards getting multiple windows to work properly.

**Comment by kzhuang1** [comment]
It seems the blanking bug is that when a window is placed ontop of another, the overlap is blanked and it is not redrawn when the overlying plot is moved away, when you make another plot it does a full redraw of all visible windows and fixes the blanking on anything not being covered.

**Comment by kzhuang1** [comment]
I have solved the issue myself by creating a new thread process for each plot call, all window functions work and I can spawn as many windows as I want.
